[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About Me"
  url = "about/"
  weight = -109

[[main]]
  name = "My Work"
  url = "myWork/"  
  weight = -108

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Media Links"
  identifier = "Links"
  weight = -107
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/migus-wong/"
  [[main]]
  parent = "Links"
  name = "Github"
  url = "https://github.com/miguswong"


# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/miguswong"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/migus-wong/"
[[social]]
name = "rss"
weight = 4
url = "index.xml"


# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"
# name = "discord"
# url = "https://discord.gg/#"